name: Create Flatpak

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  flatpak:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Flatpak
      run: |
        sudo apt install flatpak flatpak-builder xvfb

    - name: Setup Flatpak
      run: |
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install flathub org.gnome.Platform//3.36 org.gnome.Sdk//3.36 -y

    - name: Build Flatpak
      run: |
        flatpak-builder build-dir io.github.thinkle.Gourmet.yml

    - name: Run Flatpak
      run: |
        xvfb-run flatpak-builder --run --socket=fallback-x11 --socket=pulseaudio build-dir io.github.thinkle.Gourmet.yml gourmet
     
# Until issue # 107 is fixed, in the directory Gourmet was built in, open the settings.py in the following path
# .../build-dir/files/lib/python3.8/site-packages/gourmet/settings.py
# and change line 10 to:
# ui_base = os.path.join(data_dir, 'ui')
